__LINE__=__LINE__
__FILE__=__FILE__
__COUNTER__=__COUNTER__
__cplusplus=__cplusplus => 1
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
G_BYTE_ORDER=G_BYTE_ORDER => 1234
NDEBUG=NDEBUG => 1
__STDC__=__STDC__ => 1
HAVE_PROTOTYPES=HAVE_PROTOTYPES => 1
STDC_HEADERS=STDC_HEADERS => 1
__GNUC__=__GNUC__ => 1
TARGET_API_MAC_OSX=TARGET_API_MAC_OSX => 1
__APPLE_CPP__=__APPLE_CPP__ => 1
__APPLE_CC__=__APPLE_CC__ => 1
TARGET_CPU_X86_64=TARGET_CPU_X86_64 => 1
__i386__=__i386__ => 1
__x86_64__=__x86_64__ => 1
__amd64__=__amd64__ => 1
M_I86=M_I86 => 1
_M_I86=_M_I86 => 1
_WIN32=_WIN32 => 1
__attribute__=__attribute__(x)
_FLUIDSYNTH_SYNTH_H=_FLUIDSYNTH_SYNTH_H
_FLUIDSYNTH_SFONT_H=_FLUIDSYNTH_SFONT_H
_FLUIDSYNTH_AUDIO_H=_FLUIDSYNTH_AUDIO_H
_FLUIDSYNTH_MIDI_H=_FLUIDSYNTH_MIDI_H
_FLUIDSYNTH_VOICE_H=_FLUIDSYNTH_VOICE_H
_FLUIDSYNTH_EVENT_H=_FLUIDSYNTH_EVENT_H
_FLUIDSYNTH_GEN_H=_FLUIDSYNTH_GEN_H
_FLUIDSYNTH_LADSPA_H=_FLUIDSYNTH_LADSPA_H
_FLUIDSYNTH_LOG_H=_FLUIDSYNTH_LOG_H
_FLUIDSYNTH_MISC_H=_FLUIDSYNTH_MISC_H
FLUID_OK=FLUID_OK => (0)
FLUID_FAILED=FLUID_FAILED => (-1)
_FLUIDSYNTH_MOD_H=_FLUIDSYNTH_MOD_H
_FLUIDSYNTH_SEQBIND_H=_FLUIDSYNTH_SEQBIND_H
_FLUIDSYNTH_SEQ_H=_FLUIDSYNTH_SEQ_H
FLUID_SEQ_WITH_TRACE=FLUID_SEQ_WITH_TRACE => 0
_FLUIDSYNTH_SETTINGS_H=_FLUIDSYNTH_SETTINGS_H
FLUID_HINT_BOUNDED_BELOW=FLUID_HINT_BOUNDED_BELOW => 0x1
FLUID_HINT_BOUNDED_ABOVE=FLUID_HINT_BOUNDED_ABOVE => 0x2
FLUID_HINT_TOGGLED=FLUID_HINT_TOGGLED => 0x4
FLUID_HINT_OPTIONLIST=FLUID_HINT_OPTIONLIST => 0x02
_FLUIDSYNTH_SHELL_H=_FLUIDSYNTH_SHELL_H
_FLUIDSYNTH_TYPES_H=_FLUIDSYNTH_TYPES_H
